* Cloud Preferences API

Cloud Preferences provides a RESTful API and is designed to be work with OpenStack and Rackspace Cloud.  It let's you store and manage data associated with tenants, users, devices and more.

** Overview

Cloud Preferences is built with Python and uses Tornado for the web framework providing asynchronous networking and Motor for non-blocking MongoDB support.

** Todo

- Add OpenStack Identity integration for verifying tokens
- Cleanup and optimization
- API documentation
- More error handling
- Create a client for load testing

** Installation

Install the Cloud Preferences API, Supervisor, MongoDB and Memcached:

#+BEGIN_SRC sh
apt-get install supervisor mongodb-server memcached libmemcached-dev zlib1g-dev
pip install https://github.com/treytabner/python-cloudprefs.git
#+END_SRC

** Configuration

Configuration is done at runtime or with the Supervisor configuration file.  Create ~/etc/supervisor/conf.d/cloudprefs.conf~ with the following content:

#+BEGIN_SRC conf
[program:cloudprefs]
command=python -m cloudprefs.server \
    --port=8888 \
    --identity=https://identity.api.rackspacecloud.com/v2.0 \
    --memcached=localhost
stdout_logfile=/var/log/cloudprefs.log
stderr_logfile=/var/log/cloudprefs.log
user=nobody
group=nogroup
numprocs=1
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=10
directory=/tmp
#+END_SRC

** Starting services

Once you have the configuration in place, add it to Supervisor:

#+BEGIN_SRC sh
supervisorctl update
supervisorctl status
#+END_SRC

Or you can start it up manually:

#+BEGIN_SRC sh
python -m cloudprefs.server
#+END_SRC

** Testing & examples

#+BEGIN_SRC sh
pip install httpie
echo '"secretpassword"' | http http://localhost:8888/servers/b36d8906-3b97-4e26-a501-e1f9191b8765/password X-Tenant-Id:123456
http http://localhost:8888/servers/b36d8906-3b97-4e26-a501-e1f9191b8765/password X-Tenant-Id:123456
#+END_SRC
